version: '3'
services:
  sample:
    tty: true
    image: myangular
    container_name: myangular
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./..:/data
      - /data/node_modules
    working_dir: /data
  sample-api:
    image: json-server
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./data/:/data
    working_dir: /data