#https://hub.docker.com/layers/library/node/lts-alpine3.17/images/sha256-a70f29664c2cbf96be30f5ac0da6cf28a8b2fb153bf2ee7bd1d402f4c793cb86?context=explore
FROM node:18

RUN   npm install -g @angular/cli
WORKDIR /data
EXPOSE 4200